<?php
declare(strict_types=1);

require_once __DIR__ . '/../includes/require_user.php';
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/user_portal.php';

$activePage = 'payments.php';
$userId = (int)($_SESSION['user_id'] ?? 0);
$payments = [];
$paymentDetail = null;
$portalError = '';

try {
    $pdo = db();
    $ctx = portal_resolve_client($pdo, $userId, (string)($_SESSION['user_name'] ?? 'User'));
    $clientId = (int)$ctx['client_id'];

    if ($clientId <= 0 && $ctx['party_name'] === 'User') {
        $portalError = 'Your account is not yet linked to a client record.';
    } else {
        $baseSql = "SELECT id, payment_date, reference_no, amount, payment_method, remarks as notes
            FROM public.collection
            WHERE payer_name = ?";

        $listStmt = $pdo->prepare($baseSql . ' ORDER BY payment_date DESC, id DESC');
        $listStmt->execute([$ctx['party_name']]);
        $payments = $listStmt->fetchAll() ?: [];

        $selectedPaymentId = (int)($_GET['view'] ?? $_GET['receipt_id'] ?? 0);
        if ($selectedPaymentId > 0) {
            $detailStmt = $pdo->prepare($baseSql . ' AND id = ? LIMIT 1');
            $detailStmt->execute([$ctx['party_name'], $selectedPaymentId]);
            $paymentDetail = $detailStmt->fetch() ?: null;
        }

        if ($paymentDetail && (int)($_GET['download'] ?? 0) === 1) {
            $orNo = (string)($paymentDetail['reference_no'] ?: ('OR-' . str_pad((string)$paymentDetail['id'], 5, '0', STR_PAD_LEFT)));
            $filename = 'receipt-' . preg_replace('/[^A-Za-z0-9\-]/', '_', $orNo) . '.html';

            header('Content-Type: text/html; charset=UTF-8');
            header('Content-Disposition: attachment; filename="' . $filename . '"');

            echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Official Receipt</title>';
            echo '<style>body{font-family:Arial,sans-serif;background:#f6f8fc;padding:28px;color:#1b2434}.card{max-width:640px;margin:0 auto;background:#fff;border:1px solid #d8deea;border-radius:12px;padding:24px}h1{margin:0 0 14px;font-size:22px}p{margin:6px 0}.row{display:flex;justify-content:space-between;border-bottom:1px dashed #d8deea;padding:8px 0}.label{color:#5a6476}.value{font-weight:600}</style>';
            echo '</head><body><div class="card">';
            echo '<h1>Official Receipt</h1>';
            echo '<div class="row"><span class="label">OR Number</span><span class="value">' . h($orNo) . '</span></div>';
            echo '<div class="row"><span class="label">Payment Date</span><span class="value">' . h((string)$paymentDetail['payment_date']) . '</span></div>';
            echo '<div class="row"><span class="label">Invoice No</span><span class="value">' . h((string)$paymentDetail['invoice_no']) . '</span></div>';
            echo '<div class="row"><span class="label">Amount</span><span class="value">' . peso($paymentDetail['amount']) . '</span></div>';
            echo '<div class="row"><span class="label">Payment Method</span><span class="value">' . h((string)($paymentDetail['payment_method'] ?: 'N/A')) . '</span></div>';
            echo '<div class="row"><span class="label">Reference No</span><span class="value">' . h((string)($paymentDetail['reference_no'] ?: 'N/A')) . '</span></div>';
            echo '<p style="margin-top:18px;color:#6b7384">Generated by Financial Management Module.</p>';
            echo '</div></body></html>';
            exit;
        }
    }
} catch (Throwable $e) {
    $portalError = 'Unable to load payments right now.';
}

$topbarSearchPlaceholder = 'Search payment reference...';
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Payments - ServiBoard</title>
    <link rel="stylesheet" href="/FinancialSM/assets/css/app.css">
</head>
<body>
<div class="layout">
    <?php include __DIR__ . '/../includes/sidebar_user.php'; ?>

    <main class="content" role="main">
        <?php include __DIR__ . '/../includes/header_user.php'; ?>

        <div class="page-header">
            <h1>My Payments</h1>
            <p>Review posted payments and download receipt copies.</p>
        </div>

        <?php if ($portalError !== ''): ?>
            <section class="section-card">
                <div class="alert-inline"><?= h($portalError) ?></div>
            </section>
        <?php endif; ?>

        <section class="section-card">
            <div class="sub-head">
                <h3 class="heading-reset">Payment History</h3>
                <span><?= number_format(count($payments)) ?> records</span>
            </div>
            <div class="table-wrap">
                <table class="notion-table">
                    <thead>
                    <tr>
                        <th>Payment Date</th>
                        <th>Invoice No</th>
                        <th>Amount</th>
                        <th>Payment Method</th>
                        <th>Reference No</th>
                        <th>Notes</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!$payments): ?>
                        <tr><td colspan="7">No payments available.</td></tr>
                    <?php else: ?>
                        <?php foreach ($payments as $row): ?>
                            <tr>
                                <td><?= h((string)$row['payment_date']) ?></td>
                                <td><?= h((string)$row['invoice_no']) ?></td>
                                <td><?= peso($row['amount']) ?></td>
                                <td><?= h((string)($row['payment_method'] ?: 'N/A')) ?></td>
                                <td><?= h((string)($row['reference_no'] ?: 'N/A')) ?></td>
                                <td><?= h((string)($row['notes'] ?: '-')) ?></td>
                                <td class="table-actions">
                                    <a class="btn-link" href="/FinancialSM/user/payments.php?view=<?= (int)$row['id'] ?>">View</a>
                                    <a class="btn-link" href="/FinancialSM/user/payments.php?receipt_id=<?= (int)$row['id'] ?>&download=1">Download Receipt</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </section>

        <?php if ($paymentDetail): ?>
            <?php $orNo = (string)($paymentDetail['reference_no'] ?: ('OR-' . str_pad((string)$paymentDetail['id'], 5, '0', STR_PAD_LEFT))); ?>
            <section class="section-card">
                <div class="sub-head">
                    <h3 class="heading-reset">Payment Details</h3>
                    <span><a class="back-link" href="/FinancialSM/user/payments.php?receipt_id=<?= (int)$paymentDetail['id'] ?>&download=1">Download Receipt</a></span>
                </div>

                <div class="payment-props user-meta-grid">
                    <div><span>OR Number</span><strong><?= h($orNo) ?></strong></div>
                    <div><span>Payment Date</span><strong><?= h((string)$paymentDetail['payment_date']) ?></strong></div>
                    <div><span>Invoice No</span><strong><?= h((string)$paymentDetail['invoice_no']) ?></strong></div>
                    <div><span>Amount</span><strong><?= peso($paymentDetail['amount']) ?></strong></div>
                    <div><span>Payment Method</span><strong><?= h((string)($paymentDetail['payment_method'] ?: 'N/A')) ?></strong></div>
                    <div><span>Reference No</span><strong><?= h((string)($paymentDetail['reference_no'] ?: 'N/A')) ?></strong></div>
                </div>

                <div class="receipt-preview">
                    <p><strong>Notes:</strong> <?= h((string)($paymentDetail['notes'] ?: 'No notes provided.')) ?></p>
                    <div class="form-actions">
                        <button type="button" class="btn primary" onclick="window.print()">Print Receipt</button>
                    </div>
                </div>
            </section>
        <?php endif; ?>
    </main>
</div>
</body>
</html>
